name: 'Hashnode Blog'
description: 'Pulls Your Latest Blog Post From Hasnode'

inputs:
  TYPE:
    description: "Set it to GIST if you are using this for a pinned gists"
    default: "REPOSITORY"
    required: false
  BLOG_URL:
    description: "Provide your custom blog url. or leave it empty to auto generate"
    default: ""
    required: false

  FILE:
    description: "Provide GIST ID if Type is Set To Gists or provide a valid file location"
    default: "README.md"
    required: false
  USERNAME:
    description: "Your Hashnode Username"
    default: ""
    required: true
  STYLE:
    description: "Provide Which Style You Need"
    default: 'list'
    required: false
  COUNT:
    description: "No of Latest Post To Show"
    default: "6"
    required: false

branding:
  icon: 'book-open'
  color: 'blue'

runs:
  using: 'node12'
  main: 'dist/index.js'
